name: Snyk Monitor Scanning
on:
  release:
    types: [published]
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snyk-scan-ci:
    uses: grafana/security-github-actions/.github/workflows/snyk_monitor.yml@a7ed27abb504c69482026be6e6312f42240a26b5 # main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
